//Modal
const OPEN_MODAL = "OPEN_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";
const OPEN_MODAL_ADD_PHOTO = "OPEN_MODAL_ADD_PHOTO";
const CLOSE_MODAL_ADD_PHOTO = "CLOSE_MODAL_ADD_PHOTO";
const OPEN_MODAL_DELETED_PHOTO = "OPEN_MODAL_DELETED_PHOTO";
const CLOSE_MODAL_DELETED_PHOTO = "CLOSE_MODAL_DELETED_PHOTO";

//Login
const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

//images
const FETCH_IMAGES_REQUEST = "FETCH_IMAGES_REQUEST";
const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
const FETCH_IMAGES_FAILURE = "FETCH_IMAGES_FAILURE";

export {
  OPEN_MODAL,
  CLOSE_MODAL,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  FETCH_IMAGES_REQUEST,
  FETCH_IMAGES_SUCCESS,
  FETCH_IMAGES_FAILURE,
  OPEN_MODAL_ADD_PHOTO,
  CLOSE_MODAL_ADD_PHOTO,
  CLOSE_MODAL_DELETED_PHOTO,
  OPEN_MODAL_DELETED_PHOTO,
};
